// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"KnowEase/RAG/rag_go/client"
	"KnowEase/controllers"
	"KnowEase/dao"
	"KnowEase/middleware"
	"KnowEase/routes"
	"KnowEase/services"
)

// Injectors from wire.go:

func InitializeApp() *routes.APP {
	string2 := ProvideDBConnectionString()
	db := dao.NewDB(string2)
	userDaoInterface := dao.ProvideUserDao(db)
	userService := services.NewUserService(userDaoInterface)
	emailDaoInterface := dao.ProvideEmailDao(db)
	emailService := services.NewEmailService(emailDaoInterface, userDaoInterface)
	tokenService := services.NewTokenService()
	userControllers := controllers.NewUserControllers(userService, emailService, tokenService)
	middlewareMiddleware := middleware.NewMiddleWare(tokenService)
	userSvc := routes.NewUserSvc(userControllers, middlewareMiddleware)
	likeDaoInterface := dao.ProvideLikeDao(db)
	postDaoInterface := dao.ProvidePostDao(db)
	qaDaoInterface := dao.ProvideQADao(db)
	likeService := services.NewLikeService(likeDaoInterface, postDaoInterface, userDaoInterface, qaDaoInterface)
	postService := services.NewPostService(postDaoInterface, likeDaoInterface, userDaoInterface)
	likeControllers := controllers.NewLikeControllers(likeService, postService, userService)
	postControllers := controllers.NewPostControllers(postService, likeService, emailService, userService)
	postSvc := routes.NewPostSvc(likeControllers, middlewareMiddleware, postControllers)
	ragService := rag.NewRAGService()
	qaService := services.NewQAService(qaDaoInterface, likeDaoInterface, userDaoInterface, ragService, postDaoInterface)
	qaControllers := controllers.NewQAControllers(qaService, emailService, userService, likeService, postService)
	userPageSvc := routes.NewUserPageSvc(likeControllers, middlewareMiddleware, postControllers, userControllers, qaControllers)
	qaSvc := routes.NewQASvc(qaControllers, middlewareMiddleware)
	searchDaoInterface := dao.ProvideSearchDao(db)
	searchService := services.NewSearchService(searchDaoInterface)
	searchControllers := controllers.NewSearchController(searchService)
	searchSvc := routes.NewSearchSvc(searchControllers, middlewareMiddleware)
	aiChatInterface := dao.ProvideAIChatDao(db)
	aiChatService := services.NewAIChatService(aiChatInterface, ragService)
	aiChatControllers := controllers.NewAIChatControllers(aiChatService)
	aiChatSvc := routes.NewAIChatSvc(aiChatControllers, middlewareMiddleware)
	app := routes.NewApp(userSvc, postSvc, userPageSvc, qaSvc, searchSvc, aiChatSvc)
	return app
}
